apiVersion: apps/v1
kind: Deployment
metadata:
  name: permisos-roles-deployment
  labels:
    app: permisos-roles
spec:
  replicas: 2
  selector:
    matchLabels:
      app: permisos-roles
  template:
    metadata:
      labels:
        app: permisos-roles
    spec:
      containers:
      - name: permisos-roles
        image: junsy888/permisos-roles:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "sqlite:///./roles.db"
---
apiVersion: v1
kind: Service
metadata:
  name: permisos-roles-service
  labels:
    app: permisos-roles
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: permisos-roles