apiVersion: v1
kind: Service
metadata:
  name: permisos-roles-service
spec:
  selector:
    app: permisos-roles
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
  type: NodePort