name: CI/CD

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pip install pytest
        pytest app/tests/

    - name: Build Docker image
      run: |
        docker build -t permissions-roles .

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image
      run: |
        docker tag permissions-roles ${{ secrets.DOCKERHUB_USERNAME }}/permissions-roles:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/permissions-roles:latest

    - name: Deploy to Kubernetes
      if: github.ref == 'refs/heads/main'
      uses: kubernetes-sigs/kustomize-controller@v0.1.0
      with:
        kustomize-path: .
        kubeconfig: ${{ secrets.KUBECONFIG }}
