name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
      - test/ci-cd
  pull_request:
    branches:
      - main

jobs:
  # Build stage
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: Run tests
      run: |
        cd app
        python -m pytest tests/ --verbose --cov=. --cov-report=xml

    - name: Build Docker image
      run: |
        docker build -t permissions-roles:$GITHUB_SHA .

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image
      run: |
        docker tag permissions-roles:$GITHUB_SHA ${{ secrets.DOCKERHUB_USERNAME }}/permissions-roles:$GITHUB_SHA
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/permissions-roles:$GITHUB_SHA

  # Deploy stage (only on main branch)
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Kubernetes
      uses: kubernetes-sigs/kustomize-controller@v0.1.0
      with:
        kustomize-path: .
        kubeconfig: ${{ secrets.KUBECONFIG }}

    - name: Verify deployment
      run: |
        kubectl get pods
        kubectl get services
