name: CI/CD Pipeline

on:
  push:
    branches: [ main, test/ci-cd ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi pytest httpx
        pip install -r requirements.txt
        echo "Installed packages:"
        pip list
    
    - name: List directory structure
      run: |
        echo "Current directory:"
        pwd
        echo "\nFiles in current directory:"
        ls -la
        echo "\nFiles in app directory:"
        ls -la app/
        echo "\nFiles in tests directory:"
        ls -la app/tests/
        echo "\nContent of test file:"
        cat app/tests/test_main.py
    
    - name: Run tests with debug
      run: |
        cd app
        echo "Current directory before test:"
        pwd
        echo "\nPYTHONPATH before test:"
        echo $PYTHONPATH
        PYTHONPATH=$PWD pytest tests/ -v --capture=no -s
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          junsy888/permisos-roles:latest
          junsy888/permisos-roles:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
    
    - name: Deploy to Kubernetes
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml
        kubectl apply -f deployment.yml
        kubectl rollout restart deployment permisos-roles-deployment
    
    - name: Verify deployment
      run: |
        kubectl get pods -l app=permisos-roles
        kubectl get services -l app=permisos-roles
