name: CI/CD Pipeline

on:
  push:
    branches: [ main, test/ci-cd ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        pip list
    
    - name: List directory structure
      run: |
        pwd
        ls -la
        ls -la app/
        ls -la app/tests/
    
    - name: Run tests
      run: |
        cd app
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        python -m pytest tests/ -v --capture=no
